# Generated by Django 3.2.15 on 2022-09-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('vehiclenumber', models.CharField(max_length=25)),
                ('vin', models.CharField(max_length=25)),
                ('year', models.DateField()),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=100)),
                ('cc', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='result',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehiclename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.vehiclename'),
        ),
        migrations.AddField(
            model_name='cart',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.vehicle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='labadmin.booking'),
        ),
    ]
