# Generated by Django 3.2.15 on 2022-10-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0002_auto_20220922_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.AddField(
            model_name='vehiclename',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='labadmin.brand'),
        ),
    ]
