# Generated by Django 3.2.15 on 2022-10-05 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0003_auto_20221005_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclename',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labadmin.brand'),
        ),
    ]
