# Generated by Django 3.2.15 on 2022-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0007_alter_vehicle_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehiclename',
            new_name='vehiclename_id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
