# Generated by Django 3.2.15 on 2022-10-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0008_auto_20221005_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image2',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image3',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
