# Generated by Django 3.2.15 on 2022-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0009_auto_20221008_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(default='black', max_length=25),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
