# Generated by Django 3.2.15 on 2022-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0010_auto_20221018_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
