# Generated by Django 3.2.15 on 2022-10-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0011_auto_20221018_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='ptomsebastian@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='tom', max_length=25),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='general', max_length=25),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
